In [1]:
# dataset =  UCI Car evolution dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data")

NameError: name 'pd' is not defined

In [ ]:
df

      vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [ ]:
col_names= ["buying", "maint", "doors" ,"persons", 'lug_boost', 'safety', 'class']
df.columns= col_names

In [ ]:
df

     buying  maint  doors persons lug_boost safety  class
0     vhigh  vhigh      2       2     small    med  unacc
1     vhigh  vhigh      2       2     small   high  unacc
2     vhigh  vhigh      2       2       med    low  unacc
3     vhigh  vhigh      2       2       med    med  unacc
4     vhigh  vhigh      2       2       med   high  unacc
...     ...    ...    ...     ...       ...    ...    ...
1722    low    low  5more    more       med    med   good
1723    low    low  5more    more       med   high  vgood
1724    low    low  5more    more       big    low  unacc
1725    low    low  5more    more       big    med   good
1726    low    low  5more    more       big   high  vgood

[1727 rows x 7 columns]

In [1]:
df.info()

NameError: name 'df' is not defined

In [ ]:
df.describe(include='all').T       #Transposed

In [ ]:
for col in col_names:
    print(df[col].value_counts())

In [ ]:
df[df.duplicated()]

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

df['buying']= oe.fit_transform([['buying']])
df['maint']= oe.fit_transform([['maint']])
df['doors']= oe.fit_transform([['doors']])
df['lug_boost']= oe.fit_transform([['lug_boost']])
df['safety']= oe.fit_transform([['safety']])
df['class']= oe.fit_transform([['class']])

In [ ]:
X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state= 0, test_size= 0.3)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

clfl = RandomForestClassifier()

clfl.fit(X_train,y_train)

In [ ]:
pred1= clfl.predict(X_test)
pred1

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(pred1,y_test)

In [ ]:
RandomForestClassifier()